### PR TITLE
doc(VnVPlan): add section 2 and 3.7 to the VnV Plan documentation

### PR DESCRIPTION
**Pull request by jsontran**

### CODE REVIEW

**Review by katemin991 — CHANGES_REQUESTED** [review]
- section 2.4 add hyperlinks to each referenced document for easier navigation
    - i reference the dev plan in one of my sections so i think we need to include it in this section as well
- minor thing i used "V&V" instead of "VnV" which one should we stick to?

**Comment by SumanyaG** [comment]
> * section 2.4 add hyperlinks to each referenced document for easier navigation
>   
>   * i reference the dev plan in one of my sections so i think we need to include it in this section as well
> * minor thing i used "V&V" instead of "VnV" which one should we stick to?

should we continue referencing throughout the document if we have references the document before? as in, if the SRS has been linked before, should i link it again in my section?

i also used VnV and stuck to that but let me know what everyone thinks and i can change it, if needed

**Comment by jsontran** [comment]
> * section 2.4 add hyperlinks to each referenced document for easier navigation
>   
>   * i reference the dev plan in one of my sections so i think we need to include it in this section as well
> * minor thing i used "V&V" instead of "VnV" which one should we stick to?

lets stick with VnV

**Comment by katemin991** [comment]
> > * section 2.4 add hyperlinks to each referenced document for easier navigation
> >   
> >   * i reference the dev plan in one of my sections so i think we need to include it in this section as well
> > * minor thing i used "V&V" instead of "VnV" which one should we stick to?
> 
> should we continue referencing throughout the document if we have references the document before? as in, if the SRS has been linked before, should i link it again in my section?
> 
> i also used VnV and stuck to that but let me know what everyone thinks and i can change it, if needed

maybe we could hyperlink just the first instance of a document reference in a section but we can discuss this in the meeting

**Pull request merged**
